name: Debug Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  export-android:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup environment
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends ca-certificates git python python-openssl unzip wget zip curl openjdk-8-jdk
        
      - name: Install Godot
        run: |
          export GODOT_VERSION="3.2.3"
          export GODOT_DL_SUBDIR="3.2.3"
          export GODOT_RELEASE="stable"
          wget -q https://downloads.tuxfamily.org/godotengine/${GODOT_DL_SUBDIR}/Godot_v${GODOT_VERSION}-${GODOT_RELEASE}_linux_headless.64.zip && wget -q https://downloads.tuxfamily.org/godotengine/${GODOT_DL_SUBDIR}/Godot_v${GODOT_VERSION}-${GODOT_RELEASE}_export_templates.tpz && mkdir -v ~/.cache && mkdir -p -v ~/.config/godot && mkdir -p -v ~/.local/share/godot/templates/${GODOT_VERSION}.${GODOT_RELEASE} && unzip Godot_v${GODOT_VERSION}-${GODOT_RELEASE}_linux_headless.64.zip && sudo mv Godot_v${GODOT_VERSION}-${GODOT_RELEASE}_linux_headless.64 /usr/local/bin/godot && unzip Godot_v${GODOT_VERSION}-${GODOT_RELEASE}_export_templates.tpz && mv templates/* ~/.local/share/godot/templates/${GODOT_VERSION}.${GODOT_RELEASE} && rm -f Godot_v${GODOT_VERSION}-${GODOT_RELEASE}_export_templates.tpz Godot_v${GODOT_VERSION}-${GODOT_RELEASE}_linux_headless.64.zip

      - name: Check Project
        run: |
          cd $GITHUB_WORKSPACE
          godot --check-only -q

      - name: Install Android SDK and create debug.keystore
        run: |
          mkdir -p -v /tmp/android-sdk/cmdline-tools && cd /tmp/android-sdk/cmdline-tools && curl -fsSLO "https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip" && unzip -q sdk-tools-linux-*.zip && rm sdk-tools-linux-*.zip
          mkdir -p -v ~/.android
          echo "count=0" > ~/.android/repositories.cfg
          export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
          export PATH=$PATH:$JAVA_HOME
          yes | /tmp/android-sdk/cmdline-tools/tools/bin/sdkmanager --licenses
          yes | /tmp/android-sdk/cmdline-tools/tools/bin/sdkmanager "tools"
          yes | /tmp/android-sdk/cmdline-tools/tools/bin/sdkmanager "platform-tools"
          yes | /tmp/android-sdk/cmdline-tools/tools/bin/sdkmanager "build-tools;28.0.3"
          keytool -keyalg RSA -genkeypair -alias androiddebugkey -keypass android -keystore debug.keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -validity 9999 && mv debug.keystore /tmp/android-sdk/debug.keystore
          ls -l /tmp/android-sdk/debug.keystore
          
      - name: Setup correct editor settings
        run: |
          cd $GITHUB_WORKSPACE
          timeout 30s godot -e -q || echo Command timeout. # Creates the editor settings file
          sed 's@export/android/debug_keystore = ".*"@export/android/debug_keystore = "/tmp/android-sdk/debug.keystore"@g' -i ~/.config/godot/editor_settings-3.tres && echo OK Set Keystore editor value
          sed 's@export/android/adb = ".*"@export/android/adb = "/tmp/android-sdk/cmdline-tools/platform-tools/adb"@g' -i ~/.config/godot/editor_settings-3.tres && echo OK Set ADB value
          sed 's@export/android/jarsigner = ".*"@export/android/jarsigner = "/usr/lib/jvm/java-8-openjdk-amd64/bin/jarsigner"@g' -i ~/.config/godot/editor_settings-3.tres && echo OK Set jarsigner value
      
      - name: Export
        run: |
          # Quick check if basic settings are properly set
          grep -F "export/android/jarsigner =" ~/.config/godot/editor_settings-3.tres | grep '".*"' -o | xargs ls
          grep -F "export/android/debug_keystore =" ~/.config/godot/editor_settings-3.tres | grep '".*"' -o | xargs ls
          grep -F "export/android/adb =" ~/.config/godot/editor_settings-3.tres | grep '".*"' -o | xargs ls
          # Create directory for artifacts
          mkdir -v -p export/android
          # Change export_presets param to current correct one
          sed 's@keystore/debug=".*"@keystore/debug="/tmp/android-sdk/debug.keystore"@g' -i export_presets.cfg
          # Export
          godot --export-debug Android export/android/export-debug.apk
          ls -l export/android/export-debug.apk
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Android Debug Export
          path: export/android/export-debug.apk
      
